export const LOGIN_USER_REQUEST =  'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS =  'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE =  'LOGIN_USER_FAILURE';


// Company
export const LOAD_MAIN_COMPANY_POSTS_REQUEST = 'LOAD_MAIN_COMPANY_POSTS_REQUEST';
export const LOAD_MAIN_COMPANY_POSTS_SUCCESS = 'LOAD_MAIN_COMPANY_POSTS_SUCCESS';
export const LOAD_MAIN_COMPANY_POSTS_FAILURE = 'LOAD_MAIN_COMPANY_POSTS_FAILURE';

export const SEARCH_COMPANY_REQUEST = 'SEARCH_COMPANY_REQUEST';
export const SEARCH_COMPANY_SUCCESS = 'SEARCH_COMPANY_SUCCESS';
export const SEARCH_COMPANY_FAILURE = 'SEARCH_COMPANY_FAILURE';