// Login
export const LOGIN_USER_REQUEST =  'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS =  'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE =  'LOGIN_USER_FAILURE';

// Search
export const SEARCH_COMPANY_REQUEST = 'SEARCH_COMPANY_REQUEST';
export const SEARCH_COMPANY_SUCCESS = 'SEARCH_COMPANY_SUCCESS';
export const SEARCH_COMPANY_FAILURE = 'SEARCH_COMPANY_FAILURE';

// process
export const PROCESS_COMPANY_REQUEST = 'PROCESS_COMPANY_REQUEST';
export const PROCESS_COMPANY_SUCCESS = 'PROCESS_COMPANY_SUCCESS';
export const PROCESS_COMPANY_FAILURE = 'PROCESS_COMPANY_FAILURE';

// rank
export const LOAD_RANK_REQUEST = 'LOAD_RANK_REQUEST';
export const LOAD_RANK_SUCCESS = 'LOAD_RANK_SUCCESS';
export const LOAD_RANK_FAILURE = 'LOAD_RANK_FAILURE';

// loadRealtimeSearch
export const LOAD_REALTIME_SEARCH_REQUEST = 'LOAD_REALTIME_SEARCH_REQUEST';
export const LOAD_REALTIME_SEARCH_SUCCESS = 'LOAD_REALTIME_SEARCH_SUCCESS';
export const LOAD_REALTIME_SEARCH_FAILURE = 'LOAD_REALTIME_SEARCH_FAILURE';

// registerUser
export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

// loadUser
export const LOAD_USER_REQUEST = 'LOAD_USER_REQUEST';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_FAILURE = 'LOAD_USER_FAILURE';
